### ISSUE TITLE
CI/CD 구현

### ISSUE THREAD

**Issue by iamdap91** [3sam3garage/ant-sting#22]
## 개요
CI/CD를 구현한다.

## 작업내역
- git action을 이용하여 CI는 구현완료

## CD 방식
- docker-compose 에 크론걸고 돌리기
- CD를 아래 방식으로 ssh
```yaml
name: Deploy to Production  

on:  
  push:  
    branches:  
      - main  

jobs:  
  deploy:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v3  

      - name: SSH Deploy  
        uses: appleboy/ssh-action@v0.1.10  
        with:  
          host: ${{ secrets.SSH_HOST }}  
          username: ${{ secrets.SSH_USER }}  
          key: ${{ secrets.SSH_PRIVATE_KEY }}  
          script: |  
            docker-compose pull  
            docker-compose up -d  
```
